enabled: true

# Here can you set the name of the GUI in-game.
guiName: Daily Rewards

# Set the lore for the GUI Items on specific days.
rewards:
  day1:
    lore:
  day2:
    lore:
  day3:
    lore:
  day4:
    lore:
  day5:
    lore:
  day6:
    lore:
  day7:
    lore: