name: DailyRewards
load: POSTWORLD
version: 0.1
author: ByAlexius
main: net.byalexius.rewards.DailyRewards
api-version: 1.20

commands:
  daily:
    description: Open Daily Rewards GUI
    permission: daily.use
    usage: /daily